version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
  
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Порт по умолчанию для ASP.NET Core
    depends_on:
      - postgres
    environment:
      ConnectionStrings__DefaultConnection: "Host=localhost;Port=5432;Database=postgres;User Id=postgres;Password=dev;"
      PATH: "/root/.dotnet/tools:$PATH"  # Добавляем PATH здесь